#!/bin/sh

awk -v comaddr=$1 -v timestamp=$2 '
	BEGIN {
		FS =","; COMADDR = comaddr; TIMESTAMP = timestamp 
		TYPE["M_SP_TB_1"] = 30
		TYPE["M_ME_TF_1"] = 36
		
		OBJADDR["Zona1"] = 1; VALUE["Zona1"] = -1 
		OBJADDR["Zona2"] = 2; VALUE["Zona2"] = -1 
		OBJADDR["Zona3"] = 3; VALUE["Zona3"] = -1 
		OBJADDR["Zona4"] = 4; VALUE["Zona4"] = -1 
		OBJADDR["Akk"] 	 = 5; VALUE["Akk"]   = -1 
		OBJADDR["Set"]   = 6; VALUE["Set"]   = -1 
		OBJADDR["t="]    = 1; VALUE["t="]
	}
	
	{ 
		gsub(/\047/, "", $0)
		
		if ( ( $0 ~ /Vzayty na ohrany/ ) || ( $0 ~ /Snayty s ohrany/ ) )
			exit 2
		if ( $0 !~ /.*Zona.:.*Akk.*Set.*t=.*gradus C/ )
			exit 2
		
		gsub(/ gradus C/, "", $0)
		
		for (i = 1; i <= NF; ++i) {
			for (field in OBJADDR) { 
				if ( $i ~ field ) {
					if ( $i ~ /norma/ )
						VALUE[field] = 0
					else if ( ( $i ~ /Neispravnost/ ) || ( $i ~ /Pogar/ ) || ( $i ~ /Trevoga/ ) )
						VALUE[field] = 1
					else if ( $i ~ /Net/ )
						VALUE[field] = 1
					else if ( $i ~ /t=/ ) 
						VALUE[field] = substr($i, index($i, "=") + 1)
					
				}
			}
		}
		
		for (field in OBJADDR) 
			if ( ( field == "t=" ) && ( VALUE[field] != "" ) )
				printf("%s %s %s %s %s %s\n", COMADDR, OBJADDR[field], TYPE["M_ME_TF_1"], VALUE[field], "-", TIMESTAMP)
			else if ( VALUE[field] != -1 ) 
				printf("%s %s %s %s %s %s\n", COMADDR, OBJADDR[field], TYPE["M_SP_TB_1"], VALUE[field], "-", TIMESTAMP)
			
	}
' 

return $?
