#!/bin/sh

awk -v comaddr=$1 -v timestamp=$2 '
	BEGIN {
		FS = " "; COMADDR = comaddr; TIMESTAMP = timestamp 
		TYPE["M_SP_TB_1"] = 30
	}
	
	{ 
		value = 0
		objaddr = 0
		
		if ( $0 ~ "Взята на охрану зона" )
			objaddr = $8
		else if ( $0 ~ "Восстановление технолог. зоны" )
			objaddr = $7  
		else if ( $0 ~ "Нарушение технологической зоны" || $0 ~ "Неисправность в зоне" ) {
			objaddr = $7; value = 1
		}
		
		# TC 10
		if ( $0 ~ "Прибор закрыт" ) 
			objaddr = 10
		else if ( $0 ~ "Прибор открыт" ) {
			objaddr = 10; value = 1
		}
		
		# TC 11
		if ( $0 ~ "Сеть двести двадцать вольт включена" )
			objaddr = 11
		else if ( $0 ~ "Сеть двести двадцать вольт выключена" ) {
			objaddr = 11; value = 1  
		}

		# TC 12
		if ( $0 ~ "Аккумулятор в норме" )
			objaddr = 12
		else if ( $0 ~ "Аккумулятор отсутствует" || $0 ~ "Аккумулятор разряжен" ) {
			objaddr = 12; value = 1  
		}
		
		# Invalid data
		if ( objaddr == 0 ) 
			exit 2
		
		printf("%s %s %s %s %s %s\n", COMADDR, objaddr, TYPE["M_SP_TB_1"], value, "-", TIMESTAMP)
	}
' 

return $?
