#!/bin/sh

sed 's/\r$//' | awk -v comaddr=$1 -v timestamp=$2 '
	BEGIN {
		FS = " "; COMADDR = comaddr; TIMESTAMP = timestamp 
		TYPE["M_SP_TB_1"] = 30
		TYPE["M_ME_TF_1"] = 36
		count = 0
	}
	
	{ 
		objaddr = 0
		value = 0
		
		gsub(/,/, ".", $0)

		if ( $0 ~ "^TC" ) { #TC1-TC16
			objaddr = substr($1, 3)
			value = $2
			type = TYPE["M_SP_TB_1"]
		}
		else if ( $0 ~ "POWER" ) { #TC17
			objaddr = 17
			if ($2 == "OK")
				value = 0
			else if ( $2 == "FAULT" )
				value = 1
			type = TYPE["M_SP_TB_1"]
		}
		else if ( $0 ~ "TEMPERAT" ) { # TI1
			objaddr = 1
			value = substr($2, 1, length($2)-1)
			type = TYPE["M_ME_TF_1"]
		}
		else if ( $0 ~ "BATTERY" ) { # TI1
			objaddr = 2
			value = substr($2, 1, length($2)-1)
			type = TYPE["M_ME_TF_1"]
		}

		# Empty_data
		if ( objaddr == 0 )
			next
		
		printf("%s %s %s %s %s %s\n", COMADDR, objaddr, type, value, "-", TIMESTAMP)
		count += 1
	}
	
	END {
		if ( count == 0 )
			exit 2
	}	
' 

return $?
