#!/bin/sh

. $IECDIR/iecenv # LOGDIR, VARDIR
. $UTILS/log_utils

SUCCESS="Transfer was successful"
FAIL="Transfer failed"
CONFIRM="Ok"
cts_name=$1

sendfile()
{
	asduconv -c 3 $1 | sockwrite -d 3 -s $VARDIR/$cts_name/usocket 
}

end_defque()
{
	local status

	printf '^\n' | sockwrite -d 3 -s $VARDIR/$cts_name/usocket 
	status=$?
	logmsgtime "receive signal SIGUSR2 from quemngr (all deferred messages have been sent), send \"^\" to iecproxy" 
	logmsgtime "sockwrite return code $status" 
}

trap 'end_defque' USR2
trap 'rm -rf ${tmpdir}; exit 0' TERM 

exec 2>$LOGDIR/$cts_name/asdusend.log

while true; do 
	if read filename; then 
		/usr/bin/printf '%s\n' "$filename 1 $CONFIRM"
		logmsgtime "File name $filename from quemngr received"
		
		logmsgtime "Send file ./act/$filename to iecproxy" 
		sendfile ./act/$filename
		status=$?
		
		case "$status" in
			0) 
				/usr/bin/printf '%s\n' "$filename $status $SUCCSESS" 
				logmsgtime "file $filename was transferred successfully, return code 0" 
			;;
			2) 
				/usr/bin/printf '%s\n' "$filename $status $FAIL" 
				logmsgtime "connection with CTS lost, return code 2" 
			;;
			3) 
				logmsgtime "all deferred messages have been sent, return code 3"
			;;
			*) 
				/usr/bin/printf '%s\n' "$filename $status $FAIL" 
				logmsgtime "file $filename was not delivered, return code $status"
			;;
		esac
	fi
done
