#!/bin/sh

. $IECDIR/config/iecenv

tmpfile=$(mktemp -p "$RUNDIR" ccuserver_childpids.XXXXXX)

sigterm()
{
	local pid
	trap '' TERM CHLD

	kill -TERM "-$$" >/dev/null 2>&1

	trap '-' TERM
}

trap 'sigterm' TERM

logdir="$LOGDIR/ccuserver"
[ -d "$logdir" ] || mkdir -p "$logdir" 2>/dev/null

[ -x "$IECDIR/ccuserver_rtupoll" ] || exit 1 

while read asduaddr credentials dev description; do
	[ -d "$DB_ACT/$asduaddr" ] || mkdir -p "$DB_ACT/$asduaddr"
	ccuserver_rtupoll "$asduaddr" 2>>"$logdir/rtu_${asduaddr}.log" &
done <<-EOF
	$(cat "$RTU" | grep ccu825_gprs)
EOF

wait
