#!/bin/sh

IECDIR="/opt/iecd"
. $IECDIR/iecenv
. $UTILS/service_utils
. $UTILS/log_utils
. $UTILS/db_utils

control_time=$((2*24*3600))
objaddr_ex=1000

while read asduaddr info model identity; do
	case "$model" in 
		ccu825_sms | granit ) 
			while read fn; do 
				if [ -f "$DB_ACT/$asduaddr/$fn" ] && [ $(( $(date +%s) - $(stat --printf %Y "$DB_ACT/$asduaddr/$fn") )) -gt $control_time ]; then
					tmsig_send "$asduaddr" "$objaddr_ex" 30 0
					break
				fi
			done <<-EOF
				$(find "$DB_ACT/$asduaddr" -type f -printf "%P\n" 2>/dev/null | grep -v "$objaddr_ex")
			EOF
		;;
		* )
			true
		;;
	esac
done <<-EOF	
	$(cat $RTU)
EOF
