#!/bin/sh

IECDIR="/opt/iecd"
. $IECDIR/config/iecenv
. $UTILS/service_utils
. $UTILS/log_utils
. $UTILS/db_utils

control_time=$((2*24*3600))
objaddr_ex=1000
count=0

while read asduaddr info model identity; do
	case "$model" in 
		ccu825_sms | granit ) 
			while read fn; do 
				if ! [ -f "$DB_ACT/$asduaddr/$fn" ]; then 
					continue
				elif [ $(( $(date +%s) - $(stat --printf %Y "$DB_ACT/$asduaddr/$fn") )) -gt $control_time ]; then
					tmsig_send "$asduaddr" "$objaddr_ex" 30 0
					count=0
					break
				else
					count=$(( $count + 1 ))
				fi
			done <<-EOF
				$(find "$DB_ACT/$asduaddr" -type f -printf "%P\n" 2>/dev/null | grep -v "$objaddr_ex")
			EOF

			[ $count -gt 0 ] && tmsig_send "$asduaddr" "$objaddr_ex" 30 1 
		;;
		* )
			true
		;;
	esac
done <<-EOF	
	$(cat $RTU)
EOF
