#!/bin/sh

. $IECDIR/iecenv

tmpfile=$(mktemp -p $RUNDIR http_childpids.XXXXXX)

sigterm()
{
	local pid
	trap '' TERM CHLD

	kill -TERM "-$$" >/dev/null 2>&1

	trap '-' TERM
}

trap 'sigterm' TERM

logdir=$LOGDIR/httplog
mkdir -p $logdir

while read asduaddr credentials dev description; do
	[ -d "$DB_ACT/$asduaddr" ] || mkdir -p "$DB_ACT/$asduaddr"
	poll_ccuserver "$asduaddr" 2>>"$logdir/rtu_${asduaddr}" &
done <<-EOF
	$(cat "$RTU" | grep ccu825_gprs)
EOF

wait
