#!/bin/sh

if [ -f /opt/iecd/iecvar ]; then
	. /opt/iecd/iecvar
else
	exit 0
fi

RTUPOLL_START="0 1 * * * " # minute, hour, day of month, month, day of week

test -x $IECDIR/smsget || exit 0
test -x $IECDIR/smsdrop_verset || exit 0
test -x $IECDIR/smsdrop_granit || exit 0
test -x $IECDIR/quemngr || exit 0
test -x $IECDIR/worker || exit 0
test -x $IECDIR/asduconv || exit 0
test -x $IECDIR/asdusend || exit 0
test -x $IECDIR/ginterrog || exit 0
test -x $IECDIR/iecproxy || exit 0
test -x $IECDIR/ieclink || exit 0
test -x $IECDIR/rtupoll || exit 0
#test -x /usr/sbin/watchdog || exit 0


tmpfile=$(mktemp -p $RUNDIR childpids.XXXXXX)

sigterm()
{
	local pid 
	trap '' TERM CHLD
	
	# Если iecd будет запускаться от конкретного пользователя,
	# то по завершению демона можно просто удалять все задания с помощью crontab -r
	tasks=$(crontab -l 2>/dev/null | grep -v rtupoll)
	crontab -r
	[ -z "$tasks" ] || echo "$tasks" | crontab -
	
	jobs -p >$tmpfile
	while read pid; do
		kill -s TERM $pid >/dev/null 2>&1
	done <<-EOF
		$(cat $tmpfile)
	EOF

	trap '-' TERM
}

trap 'rm -rf $RUNDIR/*; exit 0' EXIT
trap 'sigterm' TERM

cd $IECDIR
while read cts_name cts_address cts_port; do
	mkdir -p $LOGDIR/$cts_name
	mkdir -p $VARDIR/$cts_name/work/drop
	mkdir -p $VARDIR/$cts_name/work/fail
	mkdir -p $VARDIR/$cts_name/work/in
	mkdir -p $VARDIR/$cts_name/work/act
	mkdir -p $VARDIR/$cts_name/work/df/0h0m30s
	mkdir -p $VARDIR/$cts_name/work/df/0h0m45s
	mkdir -p $VARDIR/$cts_name/work/df/0h0m60s
	
	quemngr \
		-n $cts_name \
		-d $VARDIR/$cts_name/work \
		-t $VARDIR/$cts_name/work/trigger \
		-s worker \
		-l 3 2>$LOGDIR/$cts_name/quemngr.log &
	
	QUEMNGR_PID=$! iecproxy \
		-u $VARDIR/$cts_name/socket \
		-s $cts_address \
		-p $cts_port \
		-l ieclink \
		-g ginterrog 2>$LOGDIR/$cts_name/iecproxy.log &

done <<-EOF
	$(cat $CTS_LIST | grep -v '^#' | sed '/^$/d')
EOF

exec 2>$LOGDIR/smsget.log

if [ -c $GSMDEV ]; then
	stty raw -echo -F $GSMDEV
	smsget -d -F $GSMDEV
	smsget -t 10 -g -F $GSMDEV & 
fi

crontab -l 2>/dev/null | { cat; echo "$RTUPOLL_START /opt/iecd/rtupoll $RTU_LIST 2>>$LOGDIR/rtupoll.log"; } | crontab -
# crontab /opt/iecd/iecd_crontab

wait
