#!/bin/sh

. /opt/iecd/io_utils
set_env IECDIR VARDIR RUNDIR LOGDIR SMSDROPDIR CTS_LIST GSMDEV IECD_CRONTAB

test -x $IECDIR/smsget || exit 1
test -x $IECDIR/smsdrop_verset || exit 1
test -x $IECDIR/smsdrop_granit || exit 1
test -x $IECDIR/smsdrop_ccu825 || exit 1
test -x $IECDIR/quemngr || exit 1
test -x $IECDIR/asdusend || exit 1
test -x $IECDIR/asduconv || exit 1
test -x $IECDIR/sockwrite || exit 1
test -x $IECDIR/iecproxy || exit 1
test -x $IECDIR/ieclink || exit 1
test -x $IECDIR/ginterrog || exit 1
test -x $IECDIR/rtupoll || exit 1

tmpfile=$(mktemp -p $RUNDIR childpids.XXXXXX)

sigterm()
{
	local pid 
	trap '' TERM CHLD
	
	# Если iecd будет запускаться от конкретного пользователя,
	# то по завершению демона можно просто удалять все задания с помощью crontab -r
	tasks=$(crontab -l 2>/dev/null | grep -v rtupoll)
	crontab -r
	[ -z "$tasks" ] || echo "$tasks" | crontab -
	
	jobs -p >$tmpfile
	while read pid; do
		kill -s TERM $pid >/dev/null 2>&1
	done <<-EOF
		$(cat $tmpfile)
	EOF

	trap '-' TERM
}

trap 'rm -rf $RUNDIR/*; exit 0' EXIT
trap 'sigterm' TERM

cd $IECDIR
while read cts_name cts_address cts_port; do
	mkdir -p $LOGDIR/$cts_name
	mkdir -p $VARDIR/$cts_name/work/drop
	mkdir -p $VARDIR/$cts_name/work/fail
	mkdir -p $VARDIR/$cts_name/work/in
	mkdir -p $VARDIR/$cts_name/work/act
	mkdir -p $VARDIR/$cts_name/work/df/0h0m30s
	mkdir -p $VARDIR/$cts_name/work/df/0h0m45s
	mkdir -p $VARDIR/$cts_name/work/df/0h0m60s
	
	quemngr \
		-n $cts_name \
		-d $VARDIR/$cts_name/work \
		-t $VARDIR/$cts_name/work/trigger \
		-s asdusend \
		-l 3 2>$LOGDIR/$cts_name/quemngr.log &
	
	PID_NOTIFY=$! iecproxy \
		-u $VARDIR/$cts_name/usocket \
		-s $cts_address \
		-p $cts_port \
		-l ieclink \
		-g ginterrog 2>$LOGDIR/$cts_name/iecproxy.log &

done <<-EOF
	$(cat $CTS_LIST | grep -v '^#' | sed '/^$/d')
EOF

if [ -c $GSMDEV ]; then
	stty raw -echo -F $GSMDEV
	smsget -d -F $GSMDEV 2>>$LOGDIR/smsget.log
	smsget -t 10 -g -F $GSMDEV 2>>$LOGDIR/smsget.log & 
fi

crontab $IECD_CRONTAB

wait
