#!/bin/sh

export IECDIR="/opt/iecd"
export IECDB="$IECDIR/iecdb"
export LOGDIR="$IECDIR/log"
export VARDIR="$IECDIR/var"
export SMSDROP="$VARDIR/smsdrop"
export RUNDIR="$VARDIR/run"
export RTU_LIST="$IECDIR/rtu_list.conf"
export CRTS_LIST="$IECDIR/crts_list.conf"
export GSMDEV="/dev/ttyUSB0"

test -x $IECDIR/smsget || exit 0
test -x $IECDIR/smsdrop_verset || exit 0
test -x $IECDIR/smsdrop_granit || exit 0
test -x $IECDIR/quemngr || exit 0
test -x $IECDIR/worker || exit 0
test -x $IECDIR/asduconv || exit 0
test -x $IECDIR/asdusend || exit 0
test -x $IECDIR/ginterrog || exit 0
test -x $IECDIR/iecproxy || exit 0
test -x $IECDIR/ieclink || exit 0
#test -x /usr/sbin/watchdog || exit 0


tmpfile=$(mktemp -p $RUNDIR childpids.XXXXXX)

sigterm()
{
	local pid 
	trap '' TERM CHLD
	
	jobs -p >$tmpfile
	while read pid; do
		kill $pid >/dev/null 2>&1
	done <<-EOF
		$(cat $tmpfile)
	EOF

	trap '-' TERM
}

trap 'rm -rf $RUNDIR/*; exit 0' EXIT
trap 'sigterm' TERM

cd $IECDIR
while read crts_name crts_address crts_port; do
	mkdir -p $LOGDIR/$crts_name
	mkdir -p $VARDIR/$crts_name/work/drop
	mkdir -p $VARDIR/$crts_name/work/fail
	mkdir -p $VARDIR/$crts_name/work/in
	mkdir -p $VARDIR/$crts_name/work/act
	mkdir -p $VARDIR/$crts_name/work/df/0h0m30s
	mkdir -p $VARDIR/$crts_name/work/df/0h0m45s
	mkdir -p $VARDIR/$crts_name/work/df/0h0m60s
	
	quemngr	-n $crts_name -d $VARDIR/$crts_name/work -t $VARDIR/$crts_name/work/trigger -s worker -l 3 2>$LOGDIR/$crts_name/quemngr.log &
	
	iecproxy -u $VARDIR/$crts_name/socket -s $crts_address -p $crts_port -l ieclink -g ginterrog 2>$LOGDIR/$crts_name/iecproxy.log &
done <<-EOF
	$(cat $CRTS_LIST | grep -v '^#' | sed '/^$/d')
EOF

exec 2>$LOGDIR/smsget.log

if [ -c $GSMDEV ]; then
	stty raw -echo -F $GSMDEV
	smsget -d -F $GSMDEV
	smsget -t 10 -g -F $GSMDEV & 
fi

wait
