#!/bin/sh

uncover()
{
	if echo "$1" | grep -q "-"; then 
		seq -s " " $(echo "$1" | tr - " ")
	else
		echo "$1"
	fi
}

while read genaddr ip name; do
	if [ "$name" = "mikrotik" ]; then
		while read addr type oid oidn; do 
			j=0
			for i in $(uncover $oidn); do
				rep=$(snmpget -Oqn -v2c -c public "$ip" "${oid}.$i" | cut -d " " -f 2)
				echo $genaddr $(($addr + $j)) $type $rep - time
				j=$(($j + 1))
			done
		done < oid/$name
	fi
done < rtu.conf
