#!/bin/sh

. $IECDIR/config/iecenv #LOGDIR, RTUPOLL_SHEDULE

[ -f "$POLLING_SHEDULE" ] || exit 1
CRONTAB_FILE="$RUNDIR/polling_crontab"

make_crontab()
{
	local shedule=$1	
	local time cmd

	echo 'MAILTO=""' >> "$CRONTAB_FILE"
	echo "PATH=${PATH}" >> "$CRONTAB_FILE"
	echo "IECDIR=${IECDIR}" >> "$CRONTAB_FILE"
	
	while read cmd timetable;do 
		if [ -x "${IECDIR}/${cmd}" ]; then
			echo "$timetable $cmd 2>>${LOGDIR}/${cmd}.log" >> "$CRONTAB_FILE"
		fi
	done <<-EOF
		$(cat "$POLLING_SHEDULE")
	EOF
}

sigterm()
{
	local pid 
	
	trap '' TERM
	crontab -r
	trap '-' TERM
	
	exit 0
}

trap 'sigterm' TERM

make_crontab "$POLLING_SHEDULE"
crontab "$CRONTAB_FILE"
rm "$CRONTAB_FILE"

while true; do sleep 10; done
