#!/bin/sh

set -e
. /lib/lsb/init-functions

# Must be a valid filename
NAME="rtupoll_init"
IECDIR="/opt/iecd"
PIDFILE=$IECDIR/var/run/$NAME.pid

# Full path to executable
DAEMON="/usr/bin/setsid $IECDIR/$NAME"

# Options
DAEMON_OPTS=""

# User to run the command as
USER=artem

# Work direction
WORK_DIR="$IECDIR"

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin:${IECDIR}"
export IECDIR

case "$1" in
	start)
		if status_of_proc -p $PIDFILE $DAEMON $NAME >/dev/null; then
			echo " * ${IECDIR}/${NAME} is running"; exit 0
		else	
			echo -n "Starting daemon: "$NAME
			start-stop-daemon --start --quiet -b -m --pidfile $PIDFILE --chdir $WORK_DIR --chuid $USER --exec $DAEMON -- $DAEMON_OPTS
			echo "."
		fi
        ;;
	stop)
		if status_of_proc -p $PIDFILE $DAEMON $NAME >/dev/null; then
			echo " * ${IECDIR}/${NAME} is running"
			echo -n "Stopping daemon: "$NAME
			start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
			echo "."
		else	
			kill -s 9 $(pgrep smsget) # Костыль. На всякий случай убиваем возможные зависшые процессы.
			echo "Daemon $NAME is not running."
		fi
        ;;
	restart)
        echo -n "Restarting daemon: "$NAME
        start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
        start-stop-daemon --start --quiet -b -m --pidfile $PIDFILE --chdir $WORK_DIR --chuid $USER --exec $DAEMON -- $DAEMON_OPTS
        echo "."
        ;;
	status)
        status_of_proc -p $PIDFILE $DAEMON $NAME  && exit 0 || exit $?
        ;;
	*)
        echo "Usage: "$1" {start|stop|restart|status}"
        exit 1
esac
