#!/bin/sh

. /opt/iecd/iecvar
. /opt/iecd/utils

DURATION_CALL=11
WAITING_ENDCALL=8
TIMEWAIT=6

usage()
{
	echo "Usage: $0 [-t Type -n Phone number] [RTU_LIST]"
}

rtupoll()
{
	local _type _number _response _ret 
	_type=$1
	_number=$2

	_number=8$(echo $_number | cut -c 2-11)
	
	if [ $_type = "granit" ]; then 
		if ! rwdev "$GSMDEV" "ATD${_number};" _response; then
			logmsgtime "Device $GSMDEV is not available now"	
			sleep $TIMEWAIT 
			_ret=2
		else			
			logmsgtime "Result of calling to the number $_number is $_response"
			sleep $DURATION_CALL
			
			if rwdev "$GSMDEV" "ATH0" _response; then
				logmsgtime "Result of ending call on the number $_number is $_response"
				sleep $WAITING_ENDCALL
				_ret=0
			else
				logmsgtime "Device $GSMDEV is not available now"	
				sleep $TIMEWAIT
				_ret=2
			fi	
		fi	
	fi
	# It is possible to ask a poll of other device models
	return $_ret
}

while getopts "t:n:" opt; do
    case $opt in
    t) type=$OPTARG ;;
    n) number=$OPTARG ;;
    *) usage; exit ;;
    esac
done

shift $(($OPTIND - 1))

if [ $number ]; then
	[ $type ] || type="granit"
	case $type in
	granit)
		(
			flock 9
			rtupoll $type $number
		) 9>$DEVLOCK
	;;
	esac
	# It is possible to ask a poll of other device models
	exit $?
fi

if [ $# -eq 1 ] && [ -f $1 ]; then rtu_list=$1; else usage; exit 0; fi 

while read rtu number type; do
	(
		flock 9
		rtupoll $type $number
	) 9>$DEVLOCK
done <$rtu_list
