#!/bin/sh

IECDIR=/home/artem/git-repo/iec-utils/scripts

. $IECDIR/iecenv
. $UTILS/log_utils
. $UTILS/service_utils
. $UTILS/db_utils


user="admin1@863833024072340:12345678"
url="https://ccu.sh"

asduaddr=180
#user=$2
#url=$3

getstate="/data.cgx?cmd=%7B%22Command%22:%22GetStateAndEvents%22%7D"
events="/events"
issync=0 # Флаг синхронизации с сервером ccu

syncvalue()
{
	local tmpfile code response iecvalue 
	
	response=$(curl -s -N --connect-timeout 15 --fail-early --keepalive --keepalive-time 15 --user "$user" "${url}${getstate}")
	code=$?
	case $code in
		0) 
			iecvalue=$(/usr/bin/printf '%s\n' "$response" | $PARSERS/ccu825_gprs "$asduaddr" "$(get_pctstamp)")
			case $? in
				0) 
					archdir="$DB_ARCH/$asduaddr"
					[ -d "$archdir" ] || mkdir -p "$archdir"

					tmpfile="$archdir/tmpccu"
					[ -f "$tmpfile" ] && rm "$tmpfile" 2>/dev/null

					cat - >> "$tmpfile" <<-EOF
						$iecvalue
					EOF

			#		if sync "$tmpfile" 2>/dev/null; then
			#			putqueue  "$tmpfile"
			#			putdbact  "$tmpfile"
			#			putdbarch "$tmpfile"
			#		else
			#			rm "$tmpfile" 2>/dev/null
			#		fi
					code=0
				;;
				1) 
					logmsgtime "Received message is not text in json format" 
					code=1 
				;;
			esac
		;;

		6) logmsgtime "The address of the given server could not be resolved (curl exit code = 6)."; break ;;
		7) logmsgtime "Failed to connect to host $url (curl exit code = 7)"; break ;;
		*) logmsgtime "Exit code $code" ;;
	esac
	
	return $code
}

lookevents()
{
	curl -s -N --connect-timeout 15 --fail-early --keepalive --keepalive-time 15 --user "$user" "${url}${events}" 
}

while true; do
	if syncvalue; then
		logmsgtime "Synchronization with the $url server was successful" ;; 

		curl -s -N --connect-timeout 15 --fail-early --keepalive --keepalive-time 15 --user "$user" "${url}${events}" | \
		sed -u -e '/^[[:space:]]*$/d' -e 's/^data:\(.*\)$/\1/' | \
		while read string; do 
			case "$string" in
			'{"Type":"Keepalive"}') 
				continue 
			;;
			'{"Type":"NewEvents"}') 
				syncvalue
				case $? in
					0) logmsgtime "Synchronization with the $url server was successful" ;; 
					1) logmsgtime "Synchronization with $url server failed"; break ;;
				esac
			;;
			'{"Type":"Close"}') 
				logmsgtime "Controller has disconnected. The channel will be closed." 
				break 
			;;
			*) logmsgtime "Undefined data. The channel will be closed."; break ;;
			esac
		done
		logmsgtime "Connection to the $url server closed"
	else
		logmsgtime  "Synchronization with $url server failed"
	fi
	sleep 60
	logmsgtime  "Retry sync with $url server"

done
