#!/bin/sh

. $IECDIR/iecenv #DB_ARCH, DB_ACT, RTU, CTS, VARDIR, OID
. $IECDIR/io_utils #get_pctstamp
. $IECDIR/db_utils # putdbact(), putqueue(), putdbarch()
. $IECDIR/snmp_utils # rangetosec(), getvboid(), getvbval()

usage() 
{
    echo "Usage: $0 [ -d dir ]"
    echo " "
    echo "  -d  oid file directory"
    echo " "
}

setqds()
{
	local qds=$1
	echo $qds
}

trset="1,2 0,1"

while getopts "d:" opt; do
    case $opt in
    d) oiddir=$OPTARG ;;
    *) usage; exit ;;
    esac
done

shift $(($OPTIND - 1))

[ -n "$oid" ] && OID="$oiddir"

while read asduaddr ipaddr model; do
    if [ -f "$OID/$model" ]; then
        mkdir -p $DB_ARCH/$asduaddr
		tmpfile="$DB_ARCH/$asduaddr/tmpsnmp"	
		fail=0

		while read objaddr type oidtable oidrange; do  
            j=0
			for i in $(rangetosec $oidrange); do
            	if value=$(snmpget -Oqn -v2c -c public "$ipaddr" "${oidtable}.$i" 2>/dev/null); then
					value=$(echo $value | cut -d' ' -f 2- | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
					if ! [ "$value" = "No Such Object available on this agent at this OID" ]; then
						echo $asduaddr $(($objaddr + $j)) $type $(echo $value | tr $trset) - $(get_pctstamp) >> "$tmpfile"
                	fi
				else
					fail=1
					break 2
				fi
                j=$(($j + 1))
            done
		done <"$OID/$model"

		case $fail in
		0)
			if sync "$tmpfile" 2>/dev/null; then 	
				putdbact  "$tmpfile"
				putqueue  "$tmpfile" 
				putdbarch "$tmpfile"
			fi
    	;;
		1)
			rm "$tmpfile" 2>/dev/null	
			while read objaddr type oidtable oidnum; do  
				j=0
				for i in $(uncover $oidnum); do
					echo $asduaddr $(($objaddr + $j)) $type "1" $(setqds "IV") $(get_pctstamp) >> "$tmpfile"
					j=$(($j + 1))
				done
			done <"$OID/$model"
			
			if sync "$tmpfile" 2>/dev/null; then 	
				putdbact  "$tmpfile"
				putqueue  "$tmpfile" 
				putdbarch "$tmpfile"
			fi
		;;
		esac
	fi

	rm "$tmpfile" 2>/dev/null
done <"$RTU"
