#!/bin/sh

. /opt/iecd/iecvar
. /opt/iecd/utils

TIMECALL=13
ENDCALL=8
TIMEWAIT=8
TIMEOUT_POLL="24h"
LOGFILE="$LOGDIR/rtupoll.log"

rtupoll()
{
	local _response _rtu _number _model 

	while read _rtu _number _model; do 
		_number=8$(echo $_number | cut -c 2-11)
		if [ $_model = "granit" ]; then
			if rwdev "$GSMDEV" "ATD${_number};" _response; then
				logmsgtime "Result of calling to the number $_number is $_response"
				sleep $TIMECALL
			else
				logmsgtime "Device $GSMDEV is not available now"	
				sleep $TIMEWAIT 
			fi	
			
			if rwdev "$GSMDEV" "ATH0" _response; then
				logmsgtime "Result of ending call on the number $_number is $_response"
				sleep $ENDCALL
			else
				logmsgtime "Device $GSMDEV is not available now"	
				sleep $TIMEWAIT
			fi	
			
		fi
	done <$RTU_LIST
}

exec 2>$LOGFILE	

#while true; do
	(
		flock 9
		rtupoll
	) 9>$DEVLOCK
#	sleep $TIMEOUT_POLL
#done
