#!/bin/sh

. $IECDIR/io_utils
. $IECDIR/iecenv # LOGDIR RTU_LIST GSMDEV RTUPOLL_SHEDULE

test -x $IECDIR/rtupoll_ring || exit 1
test -f $RTUPOLL_SHEDULE || exit 1

CRONTAB_FILE="$RUNDIR/rtupoll_crontab"

make_crontab()
{
	local shedule=$1	
	local time

	echo 'MAILTO=""' >> $CRONTAB_FILE

	while read time;do 
		echo "$time $IECDIR/rtupoll_ring $RTU_LIST 2>>$LOGDIR/rtupoll.log" >> $CRONTAB_FILE
	done <<-EOF
		$(cat $RTUPOLL_SHEDULE)
	EOF
	echo >> $CRONTAB_FILE
}

sigterm()
{
	local pid 
	trap '' TERM CHLD
	
	jobs -p >$tmpfile
	while read pid; do
		kill -s TERM $pid >/dev/null 2>&1
	done <<-EOF
		$(cat $tmpfile)
	EOF

	trap '-' TERM
}

#trap 'rm -rf $RUNDIR/*; exit 0' EXIT
#trap 'sigterm' TERM
# m h dom mon dow

make_crontab $RTUPOLL_SHEDULE
crontab $CRONTAB_FILE
#rm $CRONTAB_FILE

#wait
