#!/bin/sh

. $IECDIR/iecenv #DB_ARCH, DB_ACT, RTU, CTS, VARDIR, OID
. $IECDIR/io_utils #get_pctstamp
. $IECDIR/db_utils

usage() 
{
    echo "Usage: $0 [ -d dir ]"
    echo " "
    echo "  -d  oid file directory"
    echo " "
}

uncover()
{
    if echo "$1" | grep -q "-"; then 
        seq -s " " $(echo "$1" | tr - " ")
    else
        echo "$1"
    fi  
}

setqds()
{
	local qds=$1
	echo $qds
}

while getopts "d:" opt; do
    case $opt in
    d) oid=$OPTARG ;;
    *) usage; exit ;;
    esac
done

shift $(($OPTIND - 1))

[ -n "$oid" ] && OID=$oid

while read asduaddr ip model; do
    if [ -f "$OID/$model" ]; then
        mkdir -p $DB_ARCH/$asduaddr
		tmpfile="$DB_ARCH/$asduaddr/tmpsnmp"	
		fail=0

		while read objaddr type oidtable oidnum; do  
            j=0
			for i in $(uncover $oidnum); do
            	if value=$(snmpget -Oqn -v2c -c public "$ip" "${oidtable}.$i" 2>/dev/null); then
					value=$(echo $value | cut -d " " -f 2)
					echo $asduaddr $(($objaddr + $j)) $type $value - $(get_pctstamp) >> "$tmpfile"
                else
					fail=1
					break 2
				fi
                j=$(($j + 1))
            done
		done <"$OID/$model"

		case $fail in
		0)
			if sync "$tmpfile"; then 	
				putdbact  "$tmpfile"
				putqueue  "$tmpfile" 
				putdbarch "$tmpfile"
			fi
			rm "$tmpfile"	
    	;;
		1)
			rm "$tmpfile" 2>/dev/null	
			while read objaddr type oidtable oidnum; do  
				j=0
				for i in $(uncover $oidnum); do
					echo $asduaddr $(($objaddr + $j)) $type "1" $(setqds "IV") $(get_pctstamp) >> "$tmpfile"
					j=$(($j + 1))
				done
			done <"$OID/$model"
			
			if sync "$tmpfile"; then 	
				putdbact  "$tmpfile"
				putqueue  "$tmpfile" 
				putdbarch "$tmpfile"
			fi
			rm "$tmpfile"	
		;;
		esac
	fi  
done <"$RTU"
