#!/bin/sh

. $IECDIR/io_utils
. $IECDIR/iecenv # LOGDIR RTU_LIST GSMDEV RTUPOLL_SHEDULE

test -x $IECDIR/rtupoll_ring || exit 1
test -f $RTUPOLL_SHEDULE || exit 1

CRONTAB_FILE="$RUNDIR/rtupoll_crontab"

make_crontab()
{
	local shedule=$1	
	local time

	echo 'MAILTO=""' >> $CRONTAB_FILE

	while read time;do 
		echo "$time $IECDIR/rtupoll_ring $RTU_LIST 2>>$LOGDIR/rtupoll.log" >> $CRONTAB_FILE
	done <<-EOF
		$(cat $RTUPOLL_SHEDULE)
	EOF
}

sigterm()
{
	local pid 
	
	trap '' TERM CHLD
	crontab -r
	trap '-' TERM
	
	exit 0
}

trap 'sigterm' TERM

make_crontab $RTUPOLL_SHEDULE
crontab $CRONTAB_FILE
rm $CRONTAB_FILE

while true; do sleep 10; done
