#!/bin/sh

. $IECDIR/config/iecenv #DB_ACT, DB_ARCH, PARSERS, UTILS
. $UTILS/io_utils
. $UTILS/sms_utils
. $UTILS/db_utils

model=$1; asduaddr=$2; dcs=$3; scts=$4; sms=$5

timestamp=$(get_smststamp "$scts")
sms=$(smsdecode "$dcs" "$sms")

archdir="$DB_ARCH/$asduaddr"
[ -d "$archdir" ] || mkdir -p "$archdir"

tmpfile="$archdir/tmpsms"
[ -f "$tmpfile" ] && rm "$tmpfile" 2>/dev/null 

if [ -f "$PARSERS/$model" ]; then 
	iecvalue=$(/usr/bin/printf '%s\n' "$sms" | $PARSERS/$model "$asduaddr" "$timestamp")
fi

case $? in
	0)
		cat - >> "$tmpfile" <<-EOF
			$iecvalue
		EOF
		
		sync "$tmpfile" || exit 3
	;;
	1)
		exit 1 # missing parser for message $model 
	;;
	2)
		exit 2 # incorrect format
	;;
esac

exit 0
