#!/bin/sh

. /opt/iecd/io_utils
. /opt/iecd/sms_utils
set_env IECDIR DB_ACT DB_ARCH

readvalue()
{
	local comaddr timestamp
	awk -v comaddr=$1 -v timestamp=$2 '
		BEGIN {
			FS = " "; COMADDR = comaddr; TIMESTAMP = timestamp 
			TYPE["M_SP_TB_1"] = 30
		}
		
		{ 
			value = 0
			objaddr = 0
			
			if ( $0 ~ "Взята на охрану зона" )
				objaddr = $8
			else if ( $0 ~ "Восстановление технолог. зоны" )
				objaddr = $7  
			else if ( $0 ~ "Нарушение технологической зоны" || $0 ~ "Неисправность в зоне" ) {
				objaddr = $7; value = 1
			}
			
			# TC 10
			if ( $0 ~ "Прибор закрыт" ) 
				objaddr = 10
			else if ( $0 ~ "Прибор открыт" ) {
				objaddr = 10; value = 1
			}
			
			# TC 11
			if ( $0 ~ "Сеть двести двадцать вольт включена" )
				objaddr = 11
			else if ( $0 ~ "Сеть двести двадцать вольт выключена" ) {
				objaddr = 11; value = 1  
			}

			# TC 12
			if ( $0 ~ "Аккумулятор в норме" )
				objaddr = 12
			else if ( $0 ~ "Аккумулятор отсутствует" || $0 ~ "Аккумулятор разряжен" ) {
				objaddr = 12; value = 1  
			}
			
			# Invalid data
			if ( objaddr == 0 && value == 0 ) 
				exit 2
			
			printf("%s %s %s %s %s %s\n", COMADDR, objaddr, TYPE["M_SP_TB_1"], value, "-", TIMESTAMP)
		}
	' 
}

comaddr=$1; dcs=$2; scts=$3; sms=$4

sms=$(smsdecode $dcs $sms)

savedir="$DB_ARCH/$comaddr"
[ -d "$savedir" ] || mkdir -p "$savedir"

tempfile="$savedir/tempfile"
[ -f $tempfile ] && rm $tempfile 2>/dev/null 

timestamp=$(gettimestamp $scts)

if iec_value=$(/usr/bin/printf '%s\n' "$sms" | readvalue "$comaddr" "$timestamp"); then
	cat - >> $tempfile <<-EOF
		$iec_value
	EOF
	
	if sync $tempfile; then
		# Create files that will store the signal values for a general interrogation
		while read _comaddr _objaddr _type _value _qds _timestamp; do
			case $_type in
			30)
				_type=1
			;;
			36)
				_type=13
			esac
			
			[ -d $DB_ACT/$_comaddr/$_type ] || mkdir -p $DB_ACT/$_comaddr/$_type
			echo $_value $_qds > $DB_ACT/$_comaddr/$_type/$_objaddr
			sync $DB_ACT/$_comaddr/$_type/$_objaddr
		done < $tempfile
	else
		exit 1
	fi
else
	exit 2
fi
