#!/bin/sh

. /opt/iecd/io_utils
. /opt/iecd/sms_utils
set_env IECDIR DB_ACT DB_ARCH

readvalue()
{
	local _file _comaddr
	awk -v _file=$1 -v _comaddr=$2 '
		BEGIN {
			FS=" "; FILE = _file; COMADDR = _comaddr; 
			TYPE["M_SP_TB_1"] = 30
			TYPE["M_ME_TF_1"] = 36
			cmd="/bin/date \047+%S%3N:%_M:%_k:%e:%u:%_m:%y\047 | /bin/sed \047s/^0*//g; s/ //g\047"
			cmd | getline timestamp; close(cmd)
		}
		
		{ 
			objaddr = 0
			value = 0
			
			if ($0 ~ "^TC") { #TC1-TC16
				objaddr = substr($1, 3)
				value = $2
				type = TYPE["M_SP_TB_1"]
			}
			else if ( $0 ~ "POWER" ) { #TC17
				objaddr = 17
				if ($2 == "OK")
					value = 0
				else if ($2 == "FAULT")
					value = 1
				type = TYPE["M_SP_TB_1"]
			}
			else if ( $0 ~ "TEMPERAT" ) { # TI1
				objaddr = 1
				value = substr($2, 1, length($2)-1)
				type = TYPE["M_ME_TF_1"]
			}

			# Empty_data
			if (objaddr == 0)
				next
			
			printf("%s %s %s %s %s %s\n", COMADDR, objaddr, type, value, "-", timestamp) >> FILE
		}
		
		END {
			close(FILE)
		}	
	' 
}

comaddr=$1; dcs=$2; scts=$3; sms=$4

sms=$(gsmdecode $sms | tr ',' '.')

savedir="$DB_ARCH/$comaddr/$(/bin/date '+%Y-%m-%d')"
[ -d "$savedir" ] || mkdir -p "$savedir"

tempfile="$savedir/tempfile"
[ -f $tempfile ] && rm $tempfile 2>/dev/null 
touch $tempfile

if /usr/bin/printf '%s\n' "$sms" | readvalue "$tempfile" "$comaddr"; then
	if sync $tempfile; then
		# Create files that will store the signal values for a general interrogation
		while read _comaddr _objaddr _type _value _qds _timestamp; do
			case $_type in
				30)
					_type=1
				;;
				36)
					_type=13
				;;
			esac
			
			[ -d $DB_ACT/$_comaddr/$_type ] || mkdir -p $DB_ACT/$_comaddr/$_type
			echo $_value $_qds > $DB_ACT/$_comaddr/$_type/$_objaddr
			sync $DB_ACT/$_comaddr/$_type/$_objaddr
		done < $tempfile
	else
		exit 1
	fi
else
	exit 2
fi
