#!/bin/sh

. ${IECDIR}/service-func

smsparse()
{
	local _file _comaddr
	awk -v _file=$1 -v _comaddr=$2 '
		BEGIN {
			FS=","; FILE = _file; COMADDR = _comaddr; 
			TYPE["M_SP_TB_1"] = 30
			TYPE["M_ME_TF_1"] = 36
			cmd="/bin/date \047+%S%3N:%_M:%_k:%e:%u:%_m:%y\047 | /bin/sed \047s/^0*//g; s/ //g\047"

		}
		
		{ 
			for (i = 1; i <= NF; ++i) {
				if ($i ~ /norma/)
					$i = 0
				else if ($i ~ /Neispravnost/ || /Pogar/ || /Trevoga/)
					$i = 1
				else if ($i ~ /Net/)
					$i = 1
				else if ($i ~ /t=/)
					$i = substr($i, index($i, "=") + 1)
			}
			
			cmd | getline timestamp; close(cmd)	

			for (i = 1; i < NF; ++i )
				printf("%s %s %s %s %s %s\n", COMADDR, i, TYPE["M_SP_TB_1"], $i, "not_used", timestamp) >> FILE
			printf("%s %s %s %s %s %s\n", COMADDR, 1, TYPE["M_ME_TF_1"], $NF, "not_used", timestamp) >> FILE
			close(file)
		}
	' 
}

comaddr="0"
if [ ! -z $1 ]; then
	comaddr=$1
fi

read sms
if echo "$sms" | grep -q -v -e '[,:]'; then
	exit 2
fi

if echo $sms | grep -q -e 'Vzayty na ohrany' -e 'Snayty s ohrany'; then
#	echo "Subject: iec104\r\n\r\nControlled station  = ${comaddr}, ${sms}" | msmtp --debug -a komisyk@gmail.com -t -i komisyk@mail.ru >/dev/null 2>&1
	exit 2
fi

sms=$(echo $sms | sed 's/ gradus C//')
filename=$(mktemp -u -p "$SMSDROP" "${comaddr}_XXXXXX")

if printf '%s\n' "$sms" | smsparse "$filename" "$comaddr"; then
	if sync $filename; then
		# Create files that will store the signal values for a general interrogation
		while read comaddr objaddr type value qds timestamp; do
			case $type in
				30)
					type=1
					;;
				36)
					type=13
					;;
			esac
			
			if ! [ -d $IECDB/$comaddr/$type ]; then
				mkdir -p $IECDB/$comaddr/$type
			fi
			echo $value $qds > $IECDB/$comaddr/$type/$objaddr
		done < $filename
		
		mv $filename $SMSDROP/msg	
	else
		exit 1
	fi
fi
