#!/bin/sh

. /opt/iecd/io_utils
. /opt/iecd/sms_utils

usage() 
{
    echo "Usage: $0 [OPTION]... message"
    echo "  -m  Mode text/pdu"
	echo "  -n  Phone number"
    echo "  -F  Device file"
    echo " "
}

send_smstext()
{
	local number 
	local file 
	local smstext 
	local response

	/usr/bin/printf '%b' "AT+CMGS=\"${number}\"\r" >$file
	exec 3<$file
	response=$(readreply 3)
	exec 3<&-
	sleep 1

	/usr/bin/printf '%b' "${smstext}\x1A" >$file
	exec 3<$file
	response=$(readreply 3)
	echo $response
	exec 3<&-

	return 0
}

send_smspdu()
{
	local SCA="00" # Sim card contains the number of the SCA
	local SB="01" # Service Byte. Bit mask 0 0 0 00 0 01
	local MR="00" # Message Reference field
	local DA="0B91" # Destination Address: 0B - 11 digits, 91 - type international
	local PID="00" # Protocol ID
	local DCS="08" # UCS2
	local UDL="" # User Data Length. For encoding UCS2 each byte is encoded by two. Length(smstext) * 2
	local number=$1 
	local file=$2
	local smstext
	local response
	local UD
	local PDU

	read smstext

	DA=${DA}$(get_destaddr $number)
	UDL=$(dectohex $((2*${#smstext})))
	UD=$(echo "$smstext" | ucs2encode)
	PDU=${SCA}${SB}${MR}${DA}${PID}${DCS}${UDL}${UD}
	TPDU_LEN=$(((${#PDU} - 2)/2)) 
	
	/usr/bin/printf '%b' "AT+CMGS=$TPDU_LEN\r" >$file
	exec 3<$file
	response=$(readreply 3)
	exec 3<&-
	sleep 1
	
	/usr/bin/printf '%b' "$PDU\x1A" >$file
	exec 3<$file
	response=$(readreply 3)
	echo $response
	exec 3<&-

	return 0
}

while getopts "m:n:F:" opt; do
    case $opt in
    m) mode=$OPTARG ;;
    n) number=$OPTARG ;;
    F) file=$OPTARG ;; 
	*) usage; exit ;;
    esac
done

shift $(($OPTIND - 1))
read smstext

if ! [ -c "$file" ]; then
	echo "File $file is not character device"
	usage; exit 0
fi

case $mode in
	"text")
		/usr/bin/printf '%s\n' "$smstext" | send_smstext "$number" "$file"
	;;
	"pdu")
		/usr/bin/printf '%s\n' "$smstext" | send_smspdu "$number" "$file"
	;;
esac
