#!/bin/sh

. /opt/iecd/iecvar

tmpdir=$(mktemp -d /tmp/XXXXX.broker)
crts_name=$1
jobslist=${tmpdir}/jobslist
sendfiles=${tmpdir}/sendfiles

success="Transfer was successful"
fail="Transfer failed"
confirm="Ok"

sendfile()
{
	asduconv -c 3 $1 | asdusend -s $VARDIR/$crts_name/socket 
	printf "function sendfile(): send file $1 to iecproxy\n" >&2 
}

end_defque()
{
	printf 'function end_defque(): receive signal SIGUSR2, send to iecproxy ^\n' >&2 
	printf '^\n' | asdusend -s $VARDIR/$crts_name/socket 
}

sigchld()
{
	local pid state code name
	
	trap '' CHLD
	jobs -l >${jobslist}
	while read pid state; do
		if test -z "$state" || printf '%s' "$state" | grep -q '^Running\|^Stopped\|^Suspended'; then
			continue
		else
			case "$state" in
			Done*)
				code=$(printf '%s' "$state" | sed -n 's|^Done(\([0-9]\+\))$|\1|p')
				test -z $code && code=0
				name=$(sed -n "s/$pid //p" $sendfiles)
				test -n $name && sed -i "/$pid/d" $sendfiles
				case "$code" in
				0) 
					printf '%s\n' "$name $code $success" 
					;;
				2) 
					printf '%s\n' "$name $code $fail" 
					;;
				3) 
					printf 'iecbroker: %s\n' "all deffered message for general interrogarion was send to iecproxy" >&2 
					;;
				*) 
					true 
					;;
				esac
				;;
			*)
				true
				;;
			esac
		fi
	done <<-EOF
		$(sed 's/^.* \([0-9].*\)/\1/' <$jobslist)	
	EOF
	trap 'sigchld' CHLD
}

trap 'sigchld' CHLD
trap 'end_defque' USR2
trap 'rm -rf ${tmpdir}; exit 0' TERM 

exec 2>$LOGDIR/${crts_name}/iecbroker.log
while true; do 
	if read filename; then 
		printf '%s\n' "$filename 1 $confirm"
		sendfile ./act/$filename & #2>>$LOGDIR/${crts_name}/iecbroker.log 1>&2 & 
		printf "iecbroker: send ./act/$filename from asdusend to iecproxy\n" >&2 
		printf '%s %s\n' $! $filename >> $sendfiles
	fi
done
